# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pm-n8n

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version to build this image with.'
        type: choice
        required: true
        default: '20'
        options:
          - '18'
          - '20'
          - '22'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://drn8n.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3005a65de57f4f6eb055260dcff51360 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_db2f3d118d2640418db7efe09b92f9d6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: drn8n.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3005a65de57f4f6eb055260dcff51360 }}/pm-n8n:${{ github.sha }}
        file: ./docker/images/n8n-custom/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pm-n8n'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f136065459a044a29d4c853479374986 }}
        images: 'drn8n.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3005a65de57f4f6eb055260dcff51360 }}/pm-n8n:${{ github.sha }}'
